In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3])

In [4]:
# dimensions and shape of an array
arr.ndim

1

In [6]:
arr = np.array(20)
arr.ndim

0

In [10]:
a = np.array([[[[]]]])
a.ndim
a.shape

(1, 1, 1, 0)

In [12]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [14]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
arr = np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
arr = np.logspace(1,3,3)
arr

array([  10.,  100., 1000.])

In [21]:
np.logspace(1,3,12)

array([  10.        ,   15.19911083,   23.101297  ,   35.11191734,
         53.36699231,   81.11308308,  123.28467394,  187.38174229,
        284.80358684,  432.87612811,  657.93322466, 1000.        ])

In [22]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [24]:
arr = np.zeros([2, 3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [29]:
arr = np.ones([4,2])
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
arr = np.full(10,2)
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [33]:
arr = np.full([2,4],7)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [36]:
arr = np.empty
arr

TypeError: empty() missing required argument 'shape' (pos 0)