In [2]:
import numpy as np
from numpy.ma.core import ndim

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.__version__

'2.4.3'

In [7]:
# 0D array
arr = np.array(25)
arr

array(25)

In [8]:
# 1D array
arr = np.array([2,5,6,8,9,10])
arr

array([ 2,  5,  6,  8,  9, 10])

In [10]:
# 2D array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# 3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [12]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [13]:
a.ndim

0

In [14]:
b.ndim

1

In [15]:
c.ndim

2

In [16]:
d.ndim

3

In [19]:
arr = np.array([1,2,3,4,5], ndmin=5)
arr

array([[[[[1, 2, 3, 4, 5]]]]])

In [20]:
arr.ndim

5

In [21]:
arr = np.array([1,2,3,4,5])

In [22]:
arr[0]

np.int64(1)

In [23]:
arr[1]

np.int64(2)

In [24]:
arr[1] + arr[3]

np.int64(6)

In [25]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [26]:
arr[0,1]

np.int64(2)

In [27]:
arr[1,4]

np.int64(10)

In [28]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [29]:
arr[0,1,2]

np.int64(6)

In [30]:
arr = np.array([1,2,3,4,5])

In [31]:
arr[-1]

np.int64(5)

In [32]:
arr[1:5]

array([2, 3, 4, 5])

In [33]:
arr[1:]

array([2, 3, 4, 5])

In [34]:
arr[:3]

array([1, 2, 3])

In [35]:
arr[-3:-1]

array([3, 4])

In [36]:
arr[1:5:2]

array([2, 4])

In [37]:
arr[::2]

array([1, 3, 5])

In [38]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
arr[1,1:3]

array([5, 6])

In [40]:
arr[0:2,2]

array([3, 6])

In [41]:
arr[0:2, 1:4]

array([[2, 3],
       [5, 6]])

In [42]:
arr.dtype

dtype('int64')

In [43]:
arr = np.array(['apple', 'banana', 'cherry'])

In [44]:
arr.dtype

dtype('<U6')

In [45]:
arr = np.array([1, 2, 3, 4], dtype='S')

In [46]:
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [47]:
arr.dtype

dtype('S1')

In [48]:
arr = np.array([1, 2, 3, 4], dtype='i4')

In [49]:
arr

array([1, 2, 3, 4], dtype=int32)

In [50]:
arr.dtype

dtype('int32')

In [51]:
arr = np.array([1.1, 2.1, 3.1])

In [52]:
arr

array([1.1, 2.1, 3.1])

In [53]:
newarr = arr.astype('i')

In [54]:
newarr

array([1, 2, 3], dtype=int32)

In [55]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

In [56]:
newarr

array([ True, False,  True])

In [58]:
arr = np.array([1,2,3,4,5,6])
x = arr.copy()

In [59]:
arr

array([1, 2, 3, 4, 5, 6])

In [60]:
x

array([1, 2, 3, 4, 5, 6])

In [61]:
arr[0] = 1000

In [62]:
arr

array([1000,    2,    3,    4,    5,    6])

In [63]:
x

array([1, 2, 3, 4, 5, 6])

In [64]:
arr = np.array([1,2,3,4,5,6])
x = arr.view()

In [65]:
arr

array([1, 2, 3, 4, 5, 6])

In [66]:
x

array([1, 2, 3, 4, 5, 6])

In [67]:
arr[0] = 1000

In [68]:
arr

array([1000,    2,    3,    4,    5,    6])

In [69]:
x

array([1000,    2,    3,    4,    5,    6])

In [70]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

In [71]:
x[0] = 100

In [72]:
x

array([100,   2,   3,   4,   5])

In [73]:
arr

array([100,   2,   3,   4,   5])

In [74]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

In [76]:
print(x.base)

None


In [77]:
y.base

array([1, 2, 3, 4, 5])

In [78]:
print(y.base)

[1 2 3 4 5]
